In [1]:
import json
import pandas
import numpy

In [6]:
data=pandas.read_csv('data/initial data/CA-HepPh.txt',header=None)

In [7]:
data

                   0
0        17010\t1943
1        17010\t2489
2        17010\t3426
3        17010\t4049
4       17010\t16961
5       17010\t17897
6       17010\t26904
7       17010\t27801
8       17010\t32403
9       17010\t35262
10      17010\t40848
11      17010\t44114
12      17010\t45648
13      17010\t45654
14      17010\t47702
15      17010\t49335
16      17010\t55416
17      17010\t56358
18      17010\t64003
19      17010\t64714
20      17010\t66411
21      17010\t71844
22      17010\t72504
23      17010\t79185
24      17010\t84491
25       44114\t5874
26      44114\t14789
27      44114\t17010
28      44114\t32403
29      44114\t33245
...              ...
236980  34086\t11483
236981  34086\t17284
236982  34086\t56131
236983  34086\t75297
236984  34086\t83206
236985  34086\t86947
236986  68683\t81316
236987  81045\t19124
236988  78203\t22624
236989  78203\t46859
236990  78203\t51248
236991  42053\t23822
236992  42053\t45210
236993  40580\t75609
236994  16212\t41554
236995  16212\t66927
236996  66927\t16212
236997  66927\t41554
236998  30044\t45004
236999  30044\t71913
237000  30044\t77145
237001  77145\t30044
237002  77145\t45004
237003  77145\t71913
237004  71913\t30044
237005  71913\t45004
237006  71913\t77145
237007  42800\t74899
237008   87816\t5319
237009  87816\t38712

[237010 rows x 1 columns]